### ISSUE TITLE
How to install SPHARM-PDM on ubuntu:

### ISSUE THREAD

**Issue by sodaGH** [NIRALUser/SPHARM-PDM#26]
Thanks a lot for your sharing!
But I'm still confused with the installation and usage of SPHARM-PDM on Ubuntu. Can you show me more detail or instruction links on this problem?
Thank you!

**Comment by bpaniagua** [comment]
Hi @sodaGH 

We have a tutorial https://github.com/NIRALUser/SPHARM-PDM/blob/master/Doc/SPHARM-PDM-Tutorial.pdf describing how to install SPHARM-PDM through the Extension mechanism in Slicer as well as as part of SlicerSALT. What is exactly the problem you are having?

Please note our support forums are part of discourse, having your questions posted there will be really helpful to the rest of the community: https://discourse.slicer.org/c/community/slicer-salt


Thank you!
Bea

**Comment by sodaGH** [comment]
Hi, bpaniagua:

Thanks for your reply! I installed the SPHARM-PDM toolbox in 3D Slicer successfully. However I met another problem. I want to do the shape analysis of hippocampus on brian images, and I applied the shape analysis module in 3D Slicer. It generates several file folders like this:
![image](https://user-images.githubusercontent.com/18156614/34316659-1460977e-e7d6-11e7-8eae-d13366c84002.png)
I don't know how to use the shape analysis result, and which file should I use to do the feature selection and classification steps. You have help me a lot, and thanks for your reading. Looking forward your reply!

**Comment by bpaniagua** [comment]
Hi @sodaGH, could you please continue having your questions posted as part of our discourse forum? It will be really helpful to the rest of the community. https://discourse.slicer.org/t/shape-analysis-by-spharm-pdm/1708/4

Thank you so much!
