### ISSUE TITLE
GenParaMesh completed with errors

### ISSUE THREAD

**Issue by debinz** [NIRALUser/SPHARM-PDM#60]
Hi!

I used the SPHARM-PDM to analyze the segmented hippocampal subregion ( SlicerSALT 2.2.1 on ubuntu 18.04), I encountered an error in the Step2, GenParaMesh.
It provides a warning: 
`Euler equation not satisfied. Euler number: 16762-16762=0` 

When I check the `.nrrd` file in the `SegPostProcess` folder using itksnap, I find a hole in the 3D view of the subregion. Is there any method to fill holes? Thank you very much!

![image](https://user-images.githubusercontent.com/24296206/91968508-54d61a80-ed47-11ea-8a53-5ac6d67395fd.png)

**Comment by bpaniagua** [comment]
Hi @debinz 

SegPostProcess should take care of small holes. However, if they are very large, you will have to re-segment the object / correct the problem.

HTH
Bea

**Comment by debinz** [comment]
Thank you! Right, maybe the hole is a bit lager, is there any other automatic tool to fill these holes?

**Comment by styner** [comment]
A (bad) alternative is to repeatedly smooth it until the hole is filled. Better: load into a label editor (such as itksnap or Slicer's editor) and edit/fill the hole manually (usually takes less than 1 minute in itksnap)

**Comment by debinz** [comment]
Great！I have edited/filled the holes using itksnap and the problem has been fixed. Because I have a lot of data to process, Can this tool be run parallelly?

**Comment by styner** [comment]
You can edit one case in itksnap, while another case is running, yes

**Comment by debinz** [comment]
Yeah, because I also have many data that do not have to be edited, and if I want to run them parallelly, can this software do the job? maybe I can open many GUIs simultaneously to do it. Is there any command-line method to achieve that goal?

**Comment by bpaniagua** [comment]
Yes! You can use spharm-pdm through command line. I do this with each SPHARM step, I spin multiple workers for SegPostProcess, then GenParaMesh and finally ParaToSPHARMMesh.

Check the [SALT tutorial for SPHARM slide, 26 and beyond.](https://docs.google.com/presentation/d/1ZZ6UpONwTl_GKk66Kde9Brq0PIDujw2pKavm1RD1SBo/present?slide=id.p26)

**Comment by debinz** [comment]
I have tried the command-line method, but it always tells me that it cannot find the inpute folder. The error info is as follows,

`Path of the directory, which contains the input data dosen't exist`

I have tried three fomats that used aingle quotes, double quotes and no quote, but it still dosen't work.
Besides, sorry, I still don't understand how to run  each SPHARM step seperately by this command-line tool, and do I need to use other parallel tool such as 'GNU PARALLEL' to do the job? or the command-line can do itself by some way?

**Comment by styner** [comment]
Which module are you trying to run from the command line? SegPostProcess? Can you provide your command line?

**Comment by debinz** [comment]
I used this command-line to run the spharm-pdm:

`./SlicerSALT --no-main-window --python-script ./share/SlicerSALT-4.11/CommandLineTool/SPHARM-PDM.py ./share/SlicerSALT-4.11/CommandLineTool/SPHARM-PDM-parameters.ini`

and the settings in `SPHARM-PDM-parameters.ini` are as follows,

> [DirectoryPath]
inputDirectoryPath =/data1/CBD/hippo-surf/Adult/hippo-seg ;Path of the directory which contains the input data
outputDirectoryPath =/data1/CBD/hippo-surf/Adult/SPHARM-PDM/Sub ;Path of the directory where the output data of each step will be stored

[SegPostProcess]
rescale = True ;Enforced spacing in x,y and z direction before any processing (rescale = True or False)
space = 0.5,0.5,0.5 ;x,y and z directions for the rescale of the binary segmention input (space = x,y,z where x,y and z are floats and are between 0 and 1)
label = 2 ;Extract this label before processing (label = 0 - 100)
gauss = False ;Apply a Gaussian Filtering on the binary segmentation (gauss = True or False)
var = 10,10,10 ;Variance of Gauss filter in all 3 dimensions (var = vx,vy,vz where vx,vy and vz are integer and are between 1 and 100)

[GenParaMesh]
iter = 1000 ;Select the number of iterations to generate the parameter meshes (iter = 1 - 10000)

[ParaToSPHARMMesh]
subdivLevel = 15 ;Subdivision level for linear ikosahedron subdivision (subdivLevel = 1 - 100)
spharmDegree = 15 ;SPHARM Degree value represents the degree of the spherical harmonic series used on the data (spharmDegree = 1 - 100)
medialMesh = True ;Build the mesh that will be used to calculate the medial mesh (medialMesh = True or False)
phiIteration = 100 ;Number of phi iterations that will be used to calculate the medial mesh (phiIteration = 1 - 21474836)
thetaIteration = 100 ;Number of theta iterations that will be used to calculate the medial mesh (thetaIteration = 1 - 21474836)
regParaTemplateFileOn = False ;Use the template for parameter Registration (regParaTemplateFileOn = True or False)
regParaTemplate = path-to-registration-template ;Set a template for parameter registration (regParaTemplate need to be a VTK or VTP filepath) 
flipTemplateOn = False ;Use the fliptemplate for normalization to apply a flip on the SPHARM output (flipTemplateOn = True or False)
flipTemplate = path-to-flip-template ;This flipTemplate is used to test all possible flips of the parametrization along the first order ellipsoid axis and select the one whose reconstruction has minimal 			   ;distance to the flip-template. (flipTemplate need to be a COEF filepath)
flip = 0 ;This is rarely necessary, only in case the general first order ellipsoid heuristic fails... Flipping of the parametrization ALONG a given axis will lead to a flip of the coordinates ALONG the same axis in the ellipse aligned mesh. (0 = no flip, 1 = flip along axes of x & y, 2 = flip along y & z, 3 = flip along x & z, 4 = flip along x, 5 = flip along y, 6 = flip along x & y & z, 7 = flip along z where y is the smallest, x is the second smallest and z is the long axis of the ellipsoid)

**Comment by debinz** [comment]
And, I also find that the processing of some data will be in `GenParaMesh` step for a very long time (more than 16 hours) without errors and still cannot finish it. I have check the `.nnrd` file in the first step but I can not find any problem. Can you give me some advice about that?

**Comment by debinz** [comment]
And, I also find that the processing of some data will be in `GenParaMesh` step for a very long time (more than 16 hours) without errors and still cannot finish it. I have check the `.nnrd` file in the first step but I can not find any problem. Can you give me some advice about that?

**Comment by debinz** [comment]
And, I also find that the processing of some data will be in `GenParaMesh` step for a very long time (more than 16 hours) without errors and still cannot finish it. I have check the `.nnrd` file in the first step but I can not find any problem. Can you give me some advice about that?

**Comment by debinz** [comment]
And, I also find that the processing of some data will be in `GenParaMesh` step for a very long time (more than 16 hours) without errors and still cannot finish it. I have check the `.nnrd` file in the first step but I can not find any problem. Can you give me some advice about that?

**Comment by debinz** [comment]
And, I also find that the processing of some data will be in `GenParaMesh` step for a very long time (more than 16 hours) without errors and still cannot finish it. I have check the `.nnrd` file in the first step but I can not find any problem. Can you give me some advice about that?

**Comment by debinz** [comment]
And, I also find that the processing of some data will be in `GenParaMesh` step for a very long time (more than 16 hours) without errors and still cannot finish it. I have check the `.nnrd` file in the first step but I can not find any problem. Can you give me some advice about that?

**Comment by debinz** [comment]
And, I also find that the processing of some data will be in `GenParaMesh` step for a very long time (more than 16 hours) without errors and still cannot finish it. I have check the `.nnrd` file in the first step but I can not find any problem. Can you give me some advice about that?

**Comment by debinz** [comment]
And, I also find that the processing of some data will be in `GenParaMesh` step for a very long time (more than 16 hours) without errors and still cannot finish it. I have check the `.nnrd` file in the first step but I can not find any problem. Can you give me some advice about that?

**Comment by debinz** [comment]
And, I also find that the processing of some data will be in `GenParaMesh` step for a very long time (more than 16 hours) without errors and still cannot finish it. I have check the `.nnrd` file in the first step but I can not find any problem. Can you give me some advice about that?

**Comment by debinz** [comment]
And, I also find that the processing of some data will be in `GenParaMesh` step for a very long time (more than 16 hours) without errors and still cannot finish it. I have check the `.nnrd` file in the first step but I can not find any problem. Can you give me some advice about that?

**Comment by debinz** [comment]
And, I also find that the processing of some data will be in `GenParaMesh` step for a very long time (more than 16 hours) without errors and still cannot finish it. I have check the `.nnrd` file in the first step but I can not find any problem. Can you give me some advice about that?

**Comment by debinz** [comment]
And, I also find that the processing of some data will be in `GenParaMesh` step for a very long time (more than 16 hours) without errors and still cannot finish it. I have check the `.nnrd` file in the first step but I can not find any problem. Can you give me some advice about that?

**Comment by debinz** [comment]
And, I also find that the processing of some data will be in `GenParaMesh` step for a very long time (more than 16 hours) without errors and still cannot finish it. I have check the `.nnrd` file in the first step but I can not find any problem. Can you give me some advice about that?

**Comment by debinz** [comment]
And, I also find that the processing of some data will be in `GenParaMesh` step for a very long time (more than 16 hours) without errors and still cannot finish it. I have check the `.nnrd` file in the first step but I can not find any problem. Can you give me some advice about that?

**Comment by debinz** [comment]
And, I also find that the processing of some data will be in `GenParaMesh` step for a very long time (more than 16 hours) without errors and still cannot finish it. I have check the `.nnrd` file in the first step but I can not find any problem. Can you give me some advice about that?

**Comment by debinz** [comment]
> Yes! You can use spharm-pdm through command line. I do this with each SPHARM step, I spin multiple workers for SegPostProcess, then GenParaMesh and finally ParaToSPHARMMesh.
> 
> Check the [SALT tutorial for SPHARM slide, 26 and beyond.](https://docs.google.com/presentation/d/1ZZ6UpONwTl_GKk66Kde9Brq0PIDujw2pKavm1RD1SBo/present?slide=id.p26)

Can you tell me how to run each step separately?

**Comment by vicory** [comment]
If you want to run the steps separately through the GUI, they are under Shape Creation->Advanced in the modules drop-down menu.

You can also run them from the command line. As an example, to run GenParaMesh and its input/output arguments you can run

`./SlicerSALT --launch GenParaMeshCLP --help`

Similarly, the others are SegPostProcessCLP and ParaToSPARHMMeshCLP.

**Comment by styner** [comment]
Also check out https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3062073/ (this is for an earlier implementation of the SPHARM-PMD framework where all the tools needed to be run on the command line)

One more thing, this is really a thread for the discourse SlicerSALT page, not the github issue tracker

**Comment by debinz** [comment]
Thank you! I have tried the second step (`GenParaMesh`) by running the following,

`./SlicerSALT --launch GenParaMeshCLP --echo --verb --iter 1000 --outLogName ${line}_CHN-PD_${direction}_log --logFile --outEulerName ${line}_CHN-PD_${direction}_Euler --EulerFile ${data_dir}/${sub_name}/Step1_SegPostProcess/${line}_CHN-PD_${direction}_lfseg_corr_usegray_combine_pp.nrrd ${data_dir}/${sub_name}/Step2_GenParaMesh/${line}_CHN-PD_${direction}_lfseg_corr_usegray_combine_pp_para.vtk  ${data_dir}/${sub_name}/Step2_GenParaMesh/${line}_CHN-PD_${direction}_lfseg_corr_usegray_combine_pp_surf.vtk `

But the processing has lasted about 6.5 hours and is still not finished. I don't know what's the problem is.
By the way, @styner  do you mean I have to ask questions in other places instead of here? Anyway, thank you all very much!

**Comment by styner** [comment]
Hi, yes, I meant for you to use the SlicerSALT discourse forum page: https://discourse.slicer.org/c/community/slicer-salt

your question is a user question, which is perfect for the forum (as other users also will provide input at that place). The github page is for tool/software issues (such as bugs or possibly feature requests) but not user issues. 

Regarding your issue: something is not good with the input as there is no ouput for any iterations (you should see lots of lines for a per-iteration update). Thus something goes awry early on in the mapping. Likely you need to manually correct your input label data

**Comment by bpaniagua** [comment]
> But the processing has lasted about 6.5 hours and is still not finished. I don't know where the problem is.

What happens if you try to change the --iter parameter to something really small i.e. 10?

**Comment by debinz** [comment]
Yes, even I change the --iter parameter to 10, it still doesn't display any line for a per-iteration update. I also have checked the input `.nnrd` file but I can not find any problem, no holes, no isolated points.

**Comment by bpaniagua** [comment]
I would look for almost-holes or c-shaped areas. 
Do you see any of those?

**Comment by debinz** [comment]
sorry... what if i get this error in the log file:

`Failed /data1/CBD/hippo-surf/CBD-A/SPHARM-PDM-4/DG/Step1_SegPostProcess/CBDP0203A_CHN-PD_right_lfseg_corr_usegray_pp.nrrd /work/Stable/SLT-220-build/SPHARM-PDM/Libraries/Shape/Algorithms/BinaryMask3DEqualAreaParametricMeshSource.txx:333:
Numerical error in the parameterization, contains NaN`

**Comment by bpaniagua** [comment]
That's definitely a geometry problem. Fails to resolve the mapping.

> I would look for almost-holes or c-shaped areas. Do you see any of those?

I would look for tricky geometry. Maybe compute curvature metrics on your geometry and see if there is any place where the curvature spikes.

**Comment by debinz** [comment]
Thankyou！but some of the sub regions of hippocampus, like CA1, are C -shape, so i don't think i can midified the c-shape. Actually, I do find some nrrd files contain spike-shape and when i erased these spikes, the error was gone. Besides, dose the 'almost-hole' means areas that are very thin and may contain only one voxel in somewhat directions?
 btw, are there any tools to compute the curvature metrics on nrrd files as you said?

**Comment by allemangD** [comment]
I'm closing since there hasn't been activity here in a while. Please reach out if you still have problems.
