### ISSUE TITLE
Build fails on Ubuntu with Ninja generator

### ISSUE THREAD

**Issue by allemangD** [NIRALUser/SPHARM-PDM#66]
Environment:

- Ubuntu 20.04
- CMake 3.18.6
- Ninja 1.10.0

Abbreviated log:

```
$ cmake -B build -G 'Ninja' -D Slicer_DIR=$SLICER_NIGHTLY_DIR .
[ no errors ]
$ ninja -C build
[ ... ]
[14/17] Performing install step for 'SPHARM-PDM'
/bin/sh: 1: : Permission denied
[14/17] Forcing configure step for 'SPHARM-PDM'
FAILED: SPHARM-PDM-prefix/src/SPHARM-PDM-stamp/SPHARM-PDM-install 
cd /home/allem/src/SPHARM-PDM/build/SPHARM-PDM-build && "" "" && /snap/cmake/787/bin/cmake -E touch /home/allem/src/SPHARM-PDM/build/SPHARM-PDM-prefix/src/SPHARM-PDM-stamp/SPHARM-PDM-install
[16/17] Forcing configure step for 'SPHARM-PDM'
ninja: build stopped: subcommand failed.
```

You can see the problematic command: `... && "" "" && ...`. Obviously `"" ""` is not a valid command, so that line fails with permission denied (executable "" does not exist).

Somehow the SPHARM-PDM install step is producing this bad command and causing failures.

This occurs using Slicer Stable (`4.11.20210226`) and Nightly (`b4c6004ef` 2021-09-15). The build succeeds if using the 'Unix Makefiles' generator, so I use that as a workaround. 

```
$ cmake -B build -G 'Unix Makefiles' -D Slicer_DIR=$SLICER_NIGHTLY_DIR .
[ no errors ]
$ make -C build -j
[ ... ]
[ 94%] Performing install step for 'SPHARM-PDM'
[100%] Completed 'SPHARM-PDM'
make[2]: Leaving directory '/home/allem/src/SPHARM-PDM/build'
[100%] Built target SPHARM-PDM
make[1]: Leaving directory '/home/allem/src/SPHARM-PDM/build'
make: Leaving directory '/home/allem/src/SPHARM-PDM/build'
```

**Comment by bpaniagua** [comment]
@allemangD @vicory has this been resolved?

**Comment by allemangD** [comment]
@bpaniagua I haven't investigated further since I can workaround by using the makefiles generator, focusing on other CMF issues instead. If you'd like I will prioritize this one.

**Comment by bpaniagua** [comment]
YEs please. charge SALT for your work.

**Comment by bpaniagua** [comment]
Wonderful work. Thank you so much!
